### ISSUE TITLE
failure on different types

### ISSUE THREAD

**Issue by herodan** [nbeaver/vcard2csv#2]
I run it and if fails on additional types not specified in the script:

 params for  TEL:
    TYPE ['OTHER', 'VOICE']
Traceback (most recent call last):
  File "./vcard2csv.py", line 156, in <module>
    main()
  File "./vcard2csv.py", line 152, in main
    vcard_info = get_info_list(vcard_path)
  File "./vcard2csv.py", line 64, in get_info_list
    cell, home, work = get_phone_numbers(vCard)
  File "./vcard2csv.py", line 35, in get_phone_numbers
    if 'CELL' in tel.params['TYPE']:
KeyError: 'TYPE

**Comment by nbeaver** [comment]
Would you please attach the vCard file in question that reproduces the error, suitably anonymized?
